codigo fuente/App consulta/Controllers/RolController.cs
using App_consulta.Data;
using App_consulta.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App_consulta.Controllers
{
    public class RolController : Controller
    {
        private readonly ApplicationDbContext db;


        private RoleManager<ApplicationRole> roleManager;



        public RolController(ApplicationDbContext context, RoleManager<ApplicationRole> roleMgr)
        {
            db = context;
            roleManager = roleMgr;
        }

        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Index()
        {
            string error = (string)HttpContext.Session.GetComplex<string>("error");
            if (error != "")
            {
                ViewBag.error = error;
                HttpContext.Session.Remove("error");
            }
            var Roles = await db.Roles.ToListAsync();
            return View(Roles);
        }

        [Authorize(Policy = "Rol.Editar")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Create(ApplicationRole Rol)
        {
            var validation = await db.Roles.Where(n => n.Name == Rol.Name).CountAsync();
            if (validation > 0)
            {
                ModelState.AddModelError("", "El nombre del rol ya ha sido usado.");
                return View(Rol);
            }
            Rol.NormalizedName = Rol.Name.ToUpper();
            if (ModelState.IsValid)
            {

                db.Roles.Add(Rol);
                await db.SaveChangesAsync();

                var policies = await db.Policy.ToListAsync();
                var claims = new List<IdentityRoleClaim<string>>();
                foreach (var p in policies)
                {
                    var claim = new IdentityRoleClaim<string>();
                    claim.RoleId = Rol.Id;
                    claim.ClaimValue = "0";
                    claim.ClaimType = p.claim;
                    claims.Add(claim);

                }
                db.RoleClaims.AddRange(claims);
                await db.SaveChangesAsync();

                return RedirectToAction("Edit", new { id = Rol.Id });
            }
            return View(Rol);
        }

        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Details(string id)
        {
            ApplicationRole Rol = await db.Roles.FindAsync(id);
            if (Rol == null) { return NotFound(); }

            var permisos = await GetPermisosByRol(Rol.Id);
            ViewBag.Permisos = permisos;

            return View(Rol);
        }

        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Edit(string id)
        {
            ApplicationRole Rol = await db.Roles.FindAsync(id);
            if (Rol == null) { return NotFound(); }

            var permisos = await GetPermisosByRol(Rol.Id);
            ViewBag.Permisos = permisos;

            return View(Rol);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Edit(ApplicationRole Rol)
        {

            var validation = await db.Roles.Where(n => n.Name == Rol.Name && n.Id != Rol.Id).CountAsync();
            if (validation > 0)
            {
                ModelState.AddModelError("", "El nombre del rol ya ha sido usado.");
            }
            Rol.NormalizedName = Rol.Name.ToUpper();
            if (ModelState.IsValid && validation == 0)
            {
                db.Entry(Rol).State = EntityState.Modified;
                await db.SaveChangesAsync();

                // INICIO - Actualizar permisos
                var claims = new List<String>();
                var permisosDb = await db.RoleClaims.Where(n => n.RoleId == Rol.Id).ToListAsync();
                foreach (var per in permisosDb)
                {
                    var valor = HttpContext.Request.Form["p_" + per.Id].ToString();
                    if (valor != null)
                    {
                        claims.Add(per.ClaimType);
                        per.ClaimValue = valor == "" ? "0" : valor;
                        db.Entry(per).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                    }
                }
                //FIN - Actualizar permisos

                // INICIO - Agregar permisos para policies nuevas
                var newPolicies = await db.Policy.Where(n => !claims.Contains(n.claim)).ToListAsync();
                var newClaims = new List<IdentityRoleClaim<string>>();
                foreach (var p in newPolicies)
                {
                    var valor = HttpContext.Request.Form["n_" + p.id].ToString();

                    var claim = new IdentityRoleClaim<string>();
                    claim.RoleId = Rol.Id;
                    claim.ClaimValue = valor != null && valor != "" ? valor : "0";
                    claim.ClaimType = p.claim;
                    newClaims.Add(claim);

                }
                db.RoleClaims.AddRange(newClaims);
                await db.SaveChangesAsync();
                // FIN - Agregar permisos para policies nuevas


                return RedirectToAction("Index");
            }


            var policies = await db.Policy.ToDictionaryAsync(n => n.claim, n => n.nombre);
            var permisos = await db.RoleClaims.Where(n => n.RoleId == Rol.Id)
                .Select(n => new PermisoDataModel
                {
                    id = n.Id,
                    valor = n.ClaimValue,
                    texto = n.ClaimType
                })
                .ToListAsync();

            foreach (var per in permisos)
            {
                if (policies.ContainsKey(per.texto))
                {
                    per.texto = policies[per.texto];
                }
            }
            ViewBag.Permisos = permisos;
            return View(Rol);
        }

        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> Delete(string id)
        {
            ApplicationRole Rol = await db.Roles.FindAsync(id);
            if (Rol == null) { return NotFound(); }

            return View(Rol);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Rol.Editar")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            string error = "";
            ConfiguracionsController controlConfiguracion = new ConfiguracionsController(db);

            ApplicationRole Rol = await db.Roles.FindAsync(id);
            try
            {
                var claims = await db.RoleClaims.Where(n => n.RoleId == Rol.Id).ToListAsync();
                db.RoleClaims.RemoveRange(claims);
                await db.SaveChangesAsync();

                db.Roles.Remove(Rol);
                await db.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                error = controlConfiguracion.SqlErrorHandler(ex);
            }
            HttpContext.Session.SetComplex("error", error);

            return RedirectToAction("Index");
        }

        private async Task<List<PermisoDataModel>> GetPermisosByRol(string idRol)
        {
            //Consulta las policies y los permisos actuales del rol
            var policies = await db.Policy.ToDictionaryAsync(n => n.claim, n => n);
            var claims = new List<String>();
            var permisos = await db.RoleClaims.Where(n => n.RoleId == idRol)
                .Select(n => new PermisoDataModel
                {
                    id = n.Id,
                    valor = n.ClaimValue,
                    texto = n.ClaimType,
                    orden = 0
                })
                .ToListAsync();
            //Recorre los permisos y busca los textos dentro de las policies
            foreach (var per in permisos)
            {
                if (policies.ContainsKey(per.texto))
                {
                    claims.Add(per.texto);
                    var polAux = policies[per.texto];
                    per.texto = polAux.nombre;
                    per.orden = polAux.group;
                }
            }
            //Consulta las policies que no tengan permiso asociado y las agrega
            var newClaims = await db.Policy.Where(n => !claims.Contains(n.claim)).ToListAsync();
            foreach(var claim in newClaims)
            {
                permisos.Add(new PermisoDataModel() {
                    valor = "0",
                    texto = claim.nombre,
                    policy = claim.id,
                    orden = claim.group
                });
            }

            return permisos.OrderBy(n => n.orden).ToList();
        }

    }
    
}

codigo fuente/App consulta/Views/Shared/_Layout.cshtml
@using Microsoft.EntityFrameworkCore;

@inject App_consulta.Data.ApplicationDbContext db

@{
    var appName = "App Consulta";


    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        appName = conf.NombreApp;
    }

    var containerClass = ViewData["Fluid"] != null ? "container-fluid" : "container";

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] - @appName</title>

    <partial name="_faviconPartial" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/devexpress/dx.common.css" />
    <link rel="stylesheet" href="~/css/devexpress/dx.light.css" />

    <link rel="stylesheet" href="~/css/site.css" />

    @await RenderSectionAsync("Styles", required: false)




    <partial name="_colorMenuPartial" />
</head>
<body>
    <nav class="navbar sticky-top navbar-light bg-light navbar-expand-lg  box-shadow mb-3"
        <partial name="_imagenNavegacionPartial" /> >
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">  <partial name="_LogoPartial" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <partial name="_MenuHeaderPartial" />
        </div>
    </nav>

    <div class="bodyccs @containerClass">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div id="toastGenerico"></div>
    <div id="toastGenericoReload"></div>
    @Html.Hidden("Root", Url.Content("~/"))

    <partial name="_footerPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/devexpress/jszip.min.js"></script>
    <script src="~/js/devexpress/dx.all.js"></script>
    <script src="~/js/devexpress/dx.messages.es.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

codigo fuente/App consulta/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.EntityFrameworkCore;

@inject App_consulta.Data.ApplicationDbContext db

@{
    var appName = "App Consulta";

    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        appName = conf.NombreApp;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] - @appName</title>

    <partial name="_faviconPartial" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    @await RenderSectionAsync("Styles", required: false)
    <link rel="stylesheet" href="~/css/site.css" />

    <partial name="_colorMenuPartial" />
</head>
<body>
    <nav class="navbar sticky-top navbar-light bg-light navbar-expand-sm navbar-toggleable-sm box-shadow mb-3"
        <partial name="_imagenNavegacionPartial" /> >
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><partial name="_LogoPartial" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <partial name="_MenuHeaderPartial" />
        </div>
    </nav>
    <div class="container-fluid">
        <h2 class="titulo-principal">@ViewData["Title"]</h2>
        <div>
            <h4>@ViewData["Subtitle"]</h4>
            <hr class="mb-0" />
            <div class="row">
                <div class="col-md-2" style="background-color:#f3f3f3">
                    <partial name="_MenuAdmin" />
                </div>
                <div class="col-md-10 bg-white mt-3">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <div id="toastGenerico"></div>
    <div id="toastGenericoReload"></div>
    @Html.Hidden("Root", Url.Content("~/"))
    <partial name="_footerPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $("a#@(ViewContext.RouteData.Values["Controller"])-@(ViewContext.RouteData.Values["Action"])").addClass("active");
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

codigo fuente/App consulta/Views/Shared/_LayoutPrint.cshtml
@using Microsoft.EntityFrameworkCore;

@inject App_consulta.Data.ApplicationDbContext db

@{
    var appName = "App Consulta";

    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        appName = conf.NombreApp;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] - @appName</title>

    <partial name="_faviconPartial" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" />

    @await RenderSectionAsync("Styles", required: false)

</head>
<body>


    <div class="container bodyccs">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div id="toastGenerico"></div>
    <div id="toastGenericoReload"></div>
    @Html.Hidden("Root", Url.Content("~/"))


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

codigo fuente/App consulta/Views/Shared/_MenuAdmin.cshtml
@{

    var permisoResponsable = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Responsable.Editar" && c.Value == "1"));
    var permisoConfGeneral = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Configuracion.General" && c.Value == "1"));
    var permisoRol = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Rol.Editar" && c.Value == "1"));
    var permisoUsuario = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Usuario.Editar" && c.Value == "1"));
    var permisoLogs = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Configuracion.Logs" && c.Value == "1"));
    var permisoSolicitudes = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Solicitud.Administrar" && c.Value == "1"));
    var actualizarDatos = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Encuestas.Actualizar" && c.Value == "1"));
}
<ul class="nav nav-pills flex-column">
    <li class="nav-item">
        <a id="Configuracions-Index" asp-controller="Configuracions" asp-action="Index" class="nav-link">Inicio</a>
    </li>
    <li><hr class="dropdown-divider"></li>

    @if (permisoConfGeneral == true)
    {
        <li class="nav-item">
            <a id="Configuracions-Index2" asp-controller="Configuracions" asp-action="Index2" class="nav-link">General</a>
        </li>
    }
    @if (permisoResponsable == true)
    {
        <li class="nav-item">
            <a id="Responsables-Index2" asp-controller="Responsables" asp-action="Index2" class="nav-link">Dependencias</a>
        </li>
    }
    @if (permisoRol == true)
    {
        <li class="nav-item">
            <a id="Rol-Index" asp-controller="Rol" asp-action="Index" class="nav-link">Roles</a>
        </li>
    }
    @if (permisoUsuario == true)
    {
        <li class="nav-item">
            <a id="Users-Index" asp-controller="Users" asp-action="Index" class="nav-link">Usuarios</a>
        </li>
    }

    @if (permisoConfGeneral == true)
    {
        <li><hr class="dropdown-divider"></li>
        <li class="nav-item">
            <a id="FormalizacionConfig-Index" asp-controller="FormalizacionConfig" asp-action="Index" class="nav-link">Formalización</a>
        </li>
        <li class="nav-item">
            <a id="FormalizacionVariable-Index" asp-controller="FormalizacionVariable" asp-action="Index" class="nav-link">Variables</a>
        </li>
    }

    @if (permisoSolicitudes == true)
    {
        <li><hr class="dropdown-divider"></li>
        <li class="nav-item">
            <a id="Solicitud-IndexAdmin" asp-controller="Solicitud" asp-action="IndexAdmin" class="nav-link">Solicitudes</a>
        </li>
    }


    @if (permisoLogs == true)
    {
        <li><hr class="dropdown-divider"></li>
        <li class="nav-item">
            <a id="Logs-Index" asp-controller="Logs" asp-action="Index" class="nav-link">Registro de actividad</a>
        </li>
    }
    @if (actualizarDatos == true)
    {
        <li><hr class="dropdown-divider"></li>
        <li class="nav-item">
            <a id="Kobo-ActualizarManual" asp-controller="Kobo" asp-action="ActualizarManual" class="nav-link">Actualizar datos Kobo</a>
        </li>
    }

</ul>

codigo fuente/App consulta/Views/Shared/_MenuHeaderPartial.cshtml
<div class="collapse navbar-collapse justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
        </li>

        @if (User.HasClaim(c =>
(c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Configuracion.General" && c.Value == "1") ||
(c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Configuracion.Responsable" && c.Value == "1") ||
(c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Rol.Editar" && c.Value == "1") ||
(c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Usuario.Editar" && c.Value == "1")
))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Configuracions" asp-action="Index">Configuracion</a>
            </li>
        }
        @if (User.HasClaim(c =>(c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Encuestador.Ver" && c.Value == "1")))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Encuestador" asp-action="Index">Encuestadores</a>
            </li>
        }
        @{
            var infoEncuestas = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Encuestas.Listado" && c.Value == "1"));
            var infoFormalizacion = User.HasClaim(c => (c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/Formalizacion.Listado" && c.Value == "1"));
            
            if (infoEncuestas || infoFormalizacion)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Informes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @if (infoEncuestas)
                        {
                            <a class="dropdown-item" asp-area="" asp-controller="Informes" asp-action="Encuestados">Caracterizaciones</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Informes" asp-action="Asociaciones">Asociaciones</a>
                        }
                        @if (infoFormalizacion)
                        {
                            <a class="dropdown-item" asp-area="" asp-controller="Formalizacion" asp-action="index">Formalización</a>
                        }
                    </div>
                </li>
            }
        }
    </ul>
    <partial name="_LoginPartial" />
</div>

codigo fuente/App consulta/Views/Shared/_colorMenuPartial.cshtml
@using Microsoft.EntityFrameworkCore;

@inject App_consulta.Data.ApplicationDbContext db

@{
    var color = "#333333";
    var colorPrincipal = "#333333";
    var colorTextoPrincipal = "#ffffff";

    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {

        color = conf.ColorTextoHeader != null && conf.ColorTextoHeader != "" ? conf.ColorTextoHeader : color;


        colorPrincipal = conf.ColorPrincipal != null && conf.ColorPrincipal != "" ? conf.ColorPrincipal : colorPrincipal;

        colorTextoPrincipal = conf.ColorTextoPrincipal != "" && conf.ColorTextoPrincipal != null ? conf.ColorTextoPrincipal : colorTextoPrincipal;

    }
}


<style>
    .navbar .nav-item > a, a.navbar-brand {
        color: @color !important;
        webkit-transition: 0.15s ease-in-out;
        -moz-transition: 0.15s ease-in-out;
        -o-transition: 0.15s ease-in-out;
        transition: 0.15s ease-in-out;
    }

        .navbar .nav-item > a:hover, a.navbar-brand:hover {
            color: @color !important;
            -webkit-text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
            text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
            ;
        }


    .navbar i {
        color: @color !important;
        webkit-transition: 0.15s ease-in-out;
        -moz-transition: 0.15s ease-in-out;
        -o-transition: 0.15s ease-in-out;
        transition: 0.15s ease-in-out;
    }

        .navbar i:hover {
            color: @color !important;
            -webkit-text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
            text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
        }

        .navbar button {
        color: @color !important;
        webkit-transition: 0.15s ease-in-out;
        -moz-transition: 0.15s ease-in-out;
        -o-transition: 0.15s ease-in-out;
        transition: 0.15s ease-in-out;
    }

        .navbar button:hover {
            color: @color !important;
            -webkit-text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
            text-shadow: 0px 0px 5px rgba(0,0,0, 0.8);
        }


    .titulo-principal {
        color: @colorTextoPrincipal !important;
    }


    .btn-outline-primary {
        color: @colorPrincipal !important;
        border-color: @colorPrincipal !important;
    }

    .btn-outline-primary:hover {
        color: @color !important;
        background-color:  @colorPrincipal !important;
        border-color:  @colorPrincipal !important;
    }
</style>

codigo fuente/App consulta/Views/Shared/_faviconPartial.cshtml
@using Microsoft.EntityFrameworkCore;

@inject  App_consulta.Data.ApplicationDbContext db

@{
    var favicon = "";

    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        favicon = conf.Favicon;
    }
}

<link rel="icon" href="@Url.Content(favicon)">

codigo fuente/App consulta/Views/Shared/_footerPartial.cshtml
<footer class="border-top footer text-muted d-print-none">
    <div class="container text-center">
        Herramienta de consulta    &copy; 2021 - @DateTime.Now.Year SoliData SAS
    </div>
</footer>

codigo fuente/App consulta/Views/Shared/_formalizacionPartial.cshtml
<div class="row my-4 d-none d-print-block mx-0" >
    <div class="col-12 px-0">
        <div class="card  border-dark ">
            <div class="card-body py-1">
                <div class="d-flex">
                    <img src="@Url.Content("/images/aunap.png")" class="img-formalizacion align-self-center" />
                    <div class="my-1 mx-3 px-3 py-1 align-self-center">
                        <div class="card border-dark">
                            <div class="card-body">
                                <p class=" font-weight-bold m-0 text-center text-uppercase">
                                    CARACTERIZACIÓN, APOYO A LA FORMALIZACIÓN Y FORTALECIMIENTO
                                    ASOCIATIVO DE PESCADORES ARTESANALES CONTINENTALES
                                </p>
                            </div>
                        </div>
                        <p class="mt-1 mb-0 small">
                            Acuerdo de cooperación No. 299 / 2022
                        </p>
                    </div>

                    <img src="@Url.Content("/images/PNUD-logo-png_ES.png")" class="img-formalizacion align-self-center" />
                </div>
            </div>
        </div>
    </div>

</div>

codigo fuente/App consulta/Views/Shared/_imagenNavegacionPartial.cshtml
@using Microsoft.EntityFrameworkCore;

@inject App_consulta.Data.ApplicationDbContext db

@{
    var style = "";

    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        var imagenFondo = conf.ImgHeader;
        var colorFondo = conf.ColorPrincipal;
        if (imagenFondo != null && imagenFondo != "")
        {
            style += "background-image: url("+ imagenFondo + "); ";
        }
        else if (colorFondo != null && colorFondo != "")
        {
            style += "background-color: " + colorFondo + "!important; ";
            style += "background-image: linear-gradient(to right, rgba(0,0,0,.6), rgba(0,0,0,0), rgba(0,0,0,.6)); ";
        }
    }
}
style= '@style'

codigo fuente/App consulta/Views/Shared/_logoPartial.cshtml
@using Microsoft.EntityFrameworkCore;

@inject  App_consulta.Data.ApplicationDbContext db

@{
    var logo = "";
    var entidad = "";
    var titulo = "App";
    var conf = await db.Configuracion.FirstOrDefaultAsync();
    if (conf != null)
    {
        logo = conf.Logo;
        titulo = conf.NombrePlan;
        entidad = conf.Entidad;
    }
}

<img src="@logo" class="logo-plan"/>
<h1 class="nombre-plan ml-2">@entidad <br /><small>@titulo</small></h1>